version: '3.9'
services:
  nginx-wordpress:
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
      - mariadb
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/nginx:/etc/nginx
      - ./public:/var/www/html
  nginx-phpmyadmin:
    image: nginx:stable-alpine
    depends_on:
      - mariadb
      - phpmyadmin
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./config/nginx:/etc/nginx
      - phpmyadmin:/var/www/html
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=root
  php-fpm:
    build: ./config/php-fpm
    expose:
      - '9000'
    volumes:
      - ./config/php-fpm:/usr/local/etc/php
      - ./public:/var/www/html
  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    depends_on:
      - mariadb
    volumes:
      - phpmyadmin:/var/www/html
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
volumes:
  phpmyadmin:
    driver: local